### ISSUE TITLE
Programm not Opening at all

### ISSUE THREAD

**Issue by rafasoaresz** [NtekShadow/nft-stealer#1]
The new version is not opening, its crashing even before i open it.

**Comment by NtekShadow** [comment]
Check your Antivirus event log and see if the file got blocked by your antivirus. Avast Antivirus did so for me.

AVG already sent me an email that they flagged it as a false positive, but I don't know about other
Antivirus providers.

You can check this through this link:
https://www.virustotal.com/gui/file/5de685b136a419eb60eba032f40ac69ff661e19cfc886294fabcc3aa0d20a294

Note that this program is currently only tested for windows.
