### ISSUE TITLE
Program stopped working, close automatically

### ISSUE THREAD

**Issue by Hustler18** [NtekShadow/nft-stealer#4]
Program works well originally but Program just stopped working now, close automatically whenever i tried to download nfts.

**Comment by NtekShadow** [comment]
i am not actively developing this right now, i made it with a friend over the weekend so i have no idea if it still works or not.
Maby im gonna fix it some day but im pretty bussy sadly

https://github.com/sj-dan/OpenSea-NFT-Stealer

This project seems to be in active developement and is more likely to work!
